from app.exceptions.__base import BaseAppException


class AlreadyInUse(BaseAppException):
    pass
